### PR TITLE
Fixed extraneous instant translation

### LINKED ISSUE #267: Prevent extraneous instant translation request
With instant translation enabled, if I type a word in and click translate, I see the loading spinner and it translates.

However, within ~ 2 seconds, the instant translation will trigger since I stopped typing and it will re-translate the _same_ text. This shouldn't happen since it's an extra request and a weird interface quirk.

### PR DESCRIPTION
**Pull request by JPJPJPOPOP**
Fixes #267

### CODE REVIEW

File: assets/js/translator.js [hunk 1]
```diff
@@ -335,6 +336,8 @@ if(modeEnabled('translation')) {
                 clearTimeout(timer);
             }
 
+            translatedAlready = false;
```
Comment (sushain97) [inline assets/js/translator.js]: Is it possible to use `translateRequest` instead?

Comment (JPJPJPOPOP) [reply assets/js/translator.js]: @sushain97 Doesn't `translateRequest` go to null after translating?

Comment (sushain97) [reply assets/js/translator.js]: Ah, good point. I forgot what the original ticket was for. How about clearing the timeout once a translation request completes?

File: assets/js/translator.js [hunk 2]
```diff
@@ -6,6 +6,7 @@ var curSrcLang /*: string */, curDstLang/*: string */;
 var recentSrcLangs /*: string[] */ = [], recentDstLangs /*: string[] */ = [];
 var droppedFile/*: ?File */;
 var translateRequest;
+var timer;
```
Comment (sushain97) [inline assets/js/translator.js]: Could you call it something a bit more specific like `translationTimer` since it's a global? Also, I think it can be typed.

**Comment by sushain97** [comment]
This is great, thanks!
